/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

import java.awt.Font;
import java.awt.event.ActionListener;
import javax.swing.Timer;

// Created by SIMERA and PANGANIBAN

/**
 *
 * @author kurt
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }
    
    float num1 = 0;
    float num2 = 0;
    String operator = "";
    int numInputState = 1;
    int num1State = 1;
    
    public void resetCalculator() {
        txtIO.setText("");
        lblOperation.setText("");
        num1 = 0;
        num2 = 0;
        operator = "";
        numInputState = 1;
        num1State = 1;
        
        txtIO.setFont(new Font("Arial", Font.PLAIN, 30));
    }
    
    public String numToStr(float n){
        String string = "";
        if (n % 1 == 0)
            string = String.valueOf((int) n);
        else
            string = String.valueOf(n);
        
        return string;
    }
    
    public void setOperator(String operation) {
        try {
            if (!txtIO.getText().equals("")) {
                if (num1State == 1) {
                    num1 = Float.parseFloat(txtIO.getText());
                    num1State = 2;
                }
                else {
                    if (numInputState == 1)
                        btnEqActionPerformed(null);
                    
                    num1 = Float.parseFloat(txtIO.getText());
                }
            }
            
            operator = operation;
            num2 = num1;
            
            lblOperation.setText(numToStr(num1) + " " + operator + " ");
            numInputState = 2;
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void btnNumAction(String num, boolean fromBtn) {
        if (numInputState == 2) {
            txtIO.setText("");
        }
        numInputState = 1;
        
        if (fromBtn)
            txtIO.setText(txtIO.getText() + num);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnTimes = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnEq = new javax.swing.JButton();
        IOPanel = new javax.swing.JPanel();
        txtIO = new javax.swing.JTextField();
        lblOperation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);
        setSize(new java.awt.Dimension(365, 455));

        mainPanel.setBackground(new java.awt.Color(25, 25, 25));
        mainPanel.setMaximumSize(new java.awt.Dimension(365, 455));
        mainPanel.setMinimumSize(new java.awt.Dimension(365, 455));
        mainPanel.setPreferredSize(new java.awt.Dimension(365, 455));
        mainPanel.setLayout(null);

        btn0.setBackground(new java.awt.Color(255, 255, 255));
        btn0.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(15, 15, 15));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        mainPanel.add(btn0);
        btn0.setBounds(102, 348, 70, 70);

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(15, 15, 15));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        mainPanel.add(btn1);
        btn1.setBounds(30, 276, 70, 70);

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(15, 15, 15));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        mainPanel.add(btn2);
        btn2.setBounds(102, 276, 70, 70);

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(15, 15, 15));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        mainPanel.add(btn3);
        btn3.setBounds(174, 276, 70, 70);

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(15, 15, 15));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        mainPanel.add(btn4);
        btn4.setBounds(30, 204, 70, 70);

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(15, 15, 15));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        mainPanel.add(btn5);
        btn5.setBounds(102, 204, 70, 70);

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(15, 15, 15));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        mainPanel.add(btn6);
        btn6.setBounds(174, 204, 70, 70);

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(15, 15, 15));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        mainPanel.add(btn7);
        btn7.setBounds(30, 132, 70, 70);

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(15, 15, 15));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        mainPanel.add(btn8);
        btn8.setBounds(102, 132, 70, 70);

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(15, 15, 15));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        mainPanel.add(btn9);
        btn9.setBounds(174, 132, 70, 70);

        btnPlus.setBackground(new java.awt.Color(255, 255, 255));
        btnPlus.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(15, 15, 15));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        mainPanel.add(btnPlus);
        btnPlus.setBounds(265, 132, 70, 70);

        btnMinus.setBackground(new java.awt.Color(255, 255, 255));
        btnMinus.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(15, 15, 15));
        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        mainPanel.add(btnMinus);
        btnMinus.setBounds(265, 204, 70, 70);

        btnTimes.setBackground(new java.awt.Color(255, 255, 255));
        btnTimes.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnTimes.setForeground(new java.awt.Color(15, 15, 15));
        btnTimes.setText("×");
        btnTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimesActionPerformed(evt);
            }
        });
        mainPanel.add(btnTimes);
        btnTimes.setBounds(265, 276, 70, 70);

        btnDivide.setBackground(new java.awt.Color(255, 255, 255));
        btnDivide.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(15, 15, 15));
        btnDivide.setText("÷");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });
        mainPanel.add(btnDivide);
        btnDivide.setBounds(265, 348, 70, 70);

        btnC.setBackground(new java.awt.Color(255, 255, 255));
        btnC.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnC.setForeground(new java.awt.Color(15, 15, 15));
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        mainPanel.add(btnC);
        btnC.setBounds(30, 348, 70, 70);

        btnEq.setBackground(new java.awt.Color(0, 153, 117));
        btnEq.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnEq.setForeground(new java.awt.Color(15, 15, 15));
        btnEq.setText("=");
        btnEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqActionPerformed(evt);
            }
        });
        mainPanel.add(btnEq);
        btnEq.setBounds(174, 348, 70, 70);

        IOPanel.setBackground(new java.awt.Color(255, 255, 255));

        txtIO.setBackground(new java.awt.Color(255, 255, 255));
        txtIO.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        txtIO.setForeground(new java.awt.Color(0, 0, 0));
        txtIO.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtIO.setToolTipText("");
        txtIO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtIO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIOKeyTyped(evt);
            }
        });

        lblOperation.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblOperation.setForeground(new java.awt.Color(0, 0, 0));
        lblOperation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOperation.setToolTipText("");

        javax.swing.GroupLayout IOPanelLayout = new javax.swing.GroupLayout(IOPanel);
        IOPanel.setLayout(IOPanelLayout);
        IOPanelLayout.setHorizontalGroup(
            IOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IOPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(IOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIO, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        IOPanelLayout.setVerticalGroup(
            IOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IOPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIO, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        mainPanel.add(IOPanel);
        IOPanel.setBounds(30, 20, 305, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // TODO add your handling code here:
        setOperator("÷");
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqActionPerformed
        // TODO add your handling code here:
        if (numInputState == 1) {
            try {
                num2 = Float.parseFloat(txtIO.getText());
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        else if (numInputState == 2) {
            try {
                num1 = Float.parseFloat(txtIO.getText());
            } catch (Exception e) {
                num1 = 0;
                System.out.println(e);
            }
        }
        
        
        String ans = "";
        if (operator == "+")
            ans = numToStr(num1 + num2);
        else if (operator == "-")
            ans = numToStr(num1 - num2);
        else if (operator == "×")
            ans = numToStr(num1 * num2);
        else if (operator == "÷") {
            if (num2 == 0) {
                // Division by zero
                ActionListener listener = new ActionListener(){
                    public void actionPerformed(java.awt.event.ActionEvent evt){
                        resetCalculator();
                    }
                };
                
                ans = "Cannot divide by zero.";
                txtIO.setText(ans);
                txtIO.setFont(new Font("Arial", Font.PLAIN, 18));
                System.out.println(txtIO.getText());
                
                Timer timer = new Timer(2000, listener);
                timer.setRepeats(false);
                timer.start();
                
                return;
            }
            ans = numToStr(num1 / num2);
        }
        else {
            try {
                // Clicked equals without operation -> ans = first operand
                num1 = Float.parseFloat(txtIO.getText());
                lblOperation.setText(numToStr(num1) + " =");
                txtIO.setText(numToStr(num1));  
            } catch (Exception e) {
                // Clicked equals without operation and operands
                num1 = 0;
                lblOperation.setText(numToStr(num1) + " =");
                txtIO.setText(numToStr(num1));  
                
                System.out.println(e);
            }
            
            numInputState = 1;
            return;
        }
        
        String num1_s = numToStr(num1);
        String num2_s = numToStr(num2);
        lblOperation.setText(num1_s + " " + operator + " " + num2_s + " =");
        txtIO.setText(ans);
        numInputState = 2;
        
    }//GEN-LAST:event_btnEqActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        resetCalculator();
    }//GEN-LAST:event_btnCActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        btnNumAction("1", true);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        btnNumAction("2", true);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        btnNumAction("3", true);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimesActionPerformed
        // TODO add your handling code here:
        setOperator("×");
    }//GEN-LAST:event_btnTimesActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        btnNumAction("4", true);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        btnNumAction("5", true);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        btnNumAction("6", true);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        setOperator("-");
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
        setOperator("+");
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        btnNumAction("9", true);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        btnNumAction("8", true);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        btnNumAction("7", true);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        btnNumAction("0", true);
    }//GEN-LAST:event_btn0ActionPerformed

    private void txtIOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIOKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        
        if (key == '+')
            setOperator("+");
        else if (key == '-')
            setOperator("-");
        else if (key == '*')
            setOperator("×");
        else if (key == '/')
            setOperator("÷");
        else if (key == '\n') 
            btnEqActionPerformed(null);
        
        if(!(Character.isDigit(key)))
            evt.consume();
        else
            btnNumAction(Character.toString(key), false);
    }//GEN-LAST:event_txtIOKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IOPanel;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEq;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnTimes;
    private javax.swing.JLabel lblOperation;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtIO;
    // End of variables declaration//GEN-END:variables
}
